name: 'semver'
description: 'Provides sevmer output for current git repo'
inputs:
  debug:
    required: false
    default: false
  file:
    required: false
    default: ''
  process_dotnet:
    required: false
    default: false
outputs:
  version:
    description: Json based string with version values
    value: ${{ steps.version.outputs.json}}
runs:
  using: "composite"
  steps:
    - id: debug
      shell: bash
      if: inputs.debug
      run: |
        echo "VERSIONING_DEBUG=true" >> "$GITHUB_ENV"
    - id: set-path
      shell: bash
      run: echo ${{ github.action_path }}/bin >> $GITHUB_PATH
    - id: version
      shell: bash
      run: |
        set -o pipefail
        JSON=$(semver)
        if [[ -z ${JSON} ]]; then
          exit -1
        else
          echo "json=${JSON}" >> $GITHUB_OUTPUT
        fi
    # - id: dotnet
    #   if: inputs.process_dotnet
    #   uses: mikefarah/yq@master
    #   cmd: |
    #     echo "${{steps.version.outputs.json}}" | process_dotnet
    - id: file
      shell: bash
      if: inputs.file != ''
      run: |
        echo "${{steps.version.outputs.json}}" >> ${{inputs.file}}

      