name: 'semver'
description: 'Provides sevmer output for current git repo'
inputs:
  debug:
    required: false
    default: false
  file:
    required: false
    default: ''
outputs:
  version:
    description: Json based string with version values
    value: ${{ steps.version.outputs.json}}
runs:
  using: "composite"
  steps:
    - id: debug
      shell: bash
      if: inputs.debug
      run: |
        echo "VERSIONING_DEBUG=true" >> "$GITHUB_ENV"
    - id: version
      shell: bash
      run: |
        set -o pipefail
        echo "json=$(${{ github.action_path }}/bin/semver)" >> $GITHUB_OUTPUT
    - id: file
      shell: bash
      if: inputs.file != ''
      run: |
        echo "${{steps.version.outputs.json}}" >> ${{inputs.file}}

      