
name: CI-ASP

# ----------------------------------------------------------------------------------------------------------
# CI Pipeline for building ASP app and deplyoing it to Azure App Service
# - get config file via Rattus https://github.com/Saritasa/rattus
# - deploy to Azure App Service
# 
# Original Author: Rostislav Udaltsov
# Created: 05/11/2023
# ----------------------------------------------------------------------------------------------------------

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      BUILD_PATH:
        required: true
        type: string
      TEMPLATE_PATH:
        required: true
        type: string
      BUILD_FOLDER:
        required: true
        type: string
      PATH_TO_SOLVE_FILE:
        required: true
        type: string
      CSPROJ_FILE:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      AZURE_VAULT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      publish-profile:
        required: true

jobs:
  
  # Installing dependencies and building the application
  build:
    runs-on: windows-latest
    
    # Permissions for fetch an OIDC token for a workflow
    # More information for connect your workflows to authenticate with Azure.
    # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: cd ${{ env.BUILD_PATH }} && nuget restore ${{ env.PATH_TO_SOLVE_FILE }}
      
      - name: Download Rattus
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "saritasa/rattus"
          tag: "0.2"
          fileName: "rattus-windows-amd64.exe"
      
      - name: Render config file
        run: .\rattus-windows-amd64.exe > ${{ env.BUILD_PATH }}/Web.Debug.config
      
      - name: Build app for release
        run: msbuild ${{ env.BUILD_PATH }}/${{ env.CSPROJ_FILE }} /p:Configuration=Debug /p:Platform=AnyCPU /t:WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=${{ env.BUILD_FOLDER }}/${{ env.APP_NAME }}-${{ env.environment }}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: ${{ env.BUILD_PATH }}/${{ env.BUILD_FOLDER }}/${{ env.APP_NAME }}-${{ env.environment }}
      
  # # Generated by Azure Depoloyment Center
  # # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
  # # More GitHub Actions for Azure: https://github.com/Azure/actions
  
  # Deploying an application to azure cloud
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: '${{ env.environment }}'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app
      
      # slot-name should always be Production since there is only one available deployment slot
      # A publish profile is a file that contains information and settings for deploy applications and services in Azure Cloud
      # publish-profile is a file which is unique for each app serivce. It can be downloaded from app service's overview page on Azure portal:
      # https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.APP_NAME }}-${{ env.environment }}'
          slot-name: 'production' # deployment slot by default for new application
          # Get publish-profile from https://keys.saritasa.cloud/cred/detail/16857/
          publish-profile: ${{ secrets.publish-profile }}
          package: .
