name: CI-Wordpress

# ----------------------------------------------------------------------------------------------------------
# Pipeline rollback the release by one version on shared hosting by ansistrano ansible role
#
# Original Author: Rostislav Udaltsov
# Created: 09/25/2023
# ----------------------------------------------------------------------------------------------------------

on:
  workflow_call:
    inputs:
      # Build configuration
      server_host:
        required: true
        type: string
        description: 'The address of the server'
      ssh_deploy_user:
        type: string
        required: true
        description: 'The username for connect to production server via ssh'
      environment:
        required: true
        type: string
        description: 'The environment'
      playbook_path:
        required: true
        type: string
        description: 'The path to the file relative to the repository from which the deployment is made'
      deploy_path:
        required: true
        type: string
        description: 'The path to deploy on the production server'
      python_version:
        required: true
        type: number
        description: 'Specify the current version of Python to install the current version of ansible'
      runner:
        required: true
        type: string
        description: 'The runner on which workflow is running'
    # Secrets for ssh
    secrets:
      ssh_private_key:
        required: true
        description: 'The private key for connect to production server via ssh'

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}

    steps:
      # Preparing workspace: install python, ansible and ansistrano-role
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install Ansible
        run: |
          pip install ansible requests jinja2

      - name: Install Ansistrano roles
        run: |
          ansible-galaxy install ansistrano.deploy ansistrano.rollback

      # Adding private-key to ssh-agent
      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Adding server ip to known_hosts
      - name: Update known_hosts
        run: |
          ssh-keyscan -H ${{ inputs.server_host }} >> ~/.ssh/known_hosts

      # Deploy the project
      - name: Ansistrano rollback
        env:
          # Environment variables for ansible must be in uppercase
          ANSIBLE_GATHERING: 'smart'
          ANSIBLE_PIPELINING: True
          ANSIBLE_REMOTE_USER: ${{ inputs.SSH_DEPLOY_USER }}
        run: |
          ansible-playbook -i \
          ${{ inputs.SERVER_HOST }}, \
          ${{ inputs.PLAYBOOK_PATH }} \
          --extra-vars \
          'deploy_path=${{ inputs.DEPLOY_PATH }} \
